server:
  port: 8070
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  jackson:    serialization:      fail-on-empty-beans: false
  devtools: 
    livereload: 
      enabled: true 
    restart: 
      enabled: false #운영 에서는 제거.      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vacation?serverTimezone=Asia/Seoul
    username: shim
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop #create update none
    show-sql: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
#            client-id: 707018033376-dl9sl0vuon3ifvdra73qvnrbfcfdo98s.apps.googleusercontent.com
#            client-secret: qaC_yHa3ng2TU7aBceSAH6Au
#            scope:
#            - email
#            - profile

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'vacation-spring-boot-jwt-tutorial-secret-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: dmFjYXRpb24tc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    com.metanet.vacation: DEBUG
    